version: '3'
services:
  db:
    image: mysql:8
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306'
  web: 
    image: 'php:7.0-apache'
    restart: always
    ports:
     - '80:80'
    volumes:
      - ./app:/var/www/html